# Generated by Django 4.1.5 on 2023-05-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
