# Generated by Django 4.1.5 on 2023-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_instructor_bio_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
