# Generated by Django 4.1.5 on 2023-06-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
    ]
