# Generated by Django 4.1.5 on 2023-06-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
