# Generated by Django 4.1.5 on 2023-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='courses.Registration', to='courses.student'),
        ),
    ]
